Sprint 6
JavaScriptNoob/react-burger pull request #10
Opened 2023-06-18 17:51 UTC by JavaScriptNoob

2023-06-23 05:37 UTC, randomroot requested changes
**Добрый день!**

Вы проделали **хорошую** работу, реализовали все необходимые юнит и e2e тесты, **отлично**, что рассмотрели кейсы с отправкой заказа, **так держать** 👍 

Однако, для успешной сдачи работы, вам необходимо изучить и внести необходимые **изменения** в ваш проект, согласно комментариям к ревью, в том числе обратить особое внимание на следующие моменты:

- Следует обеспечить максимально полное покрытие редьюсеров тестами (см. https://disk.yandex.ru/i/dV9TcjpQgqHzuA). Проверить покрытие вы можете с помощью команды `npm test -- --watchAll=false --coverage`;
- Следует удалить тест `index-reducer.test.js` т.к. он падает с ошибкой из-за отсутствия в нем тестов (см. https://disk.yandex.ru/i/gWpIKam5zzwhIQ);
- После завершения процесса переноса следует проверить, что элементы действительно попали в конструктор;
- Обратите внимание, что в тестах появляется надпись "все пошло не по плану" в момент авторизации (см. https://disk.yandex.ru/i/Q9Q15OlVMetJ7g). Если всё этом хорошо - то не страшно, но лучше перепроверить код формы;
- При переходе на страницу опубликованную на Github Pages по-умолчанию открывается пустой экран, а не конструктор. Плюс, обратите внимание, что в рамках урла меняется путь полностью, а часть с `react-burger` пропадает. Необходимо донастроить этот момент, например через параметр `homepage` в `package.json`;

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и проходит тесты **успешно**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

**Успешного вам рефакторинга и хорошего настроения!** 🐈

2023-06-23 05:37 UTC, randomroot commented on cypress/e2e/component.test.cy.ts
> +        dNd(2)
🔴 **Нужно исправить:**

После завершения процесса переноса следует проверить, что элементы действительно попали в конструктор

2023-06-23 05:37 UTC, randomroot commented on cypress/e2e/component.test.cy.ts
> +    })
🟡 **Можно улучшить:**

Лучше тестировать приложение не на боевом сервере, а мокать запросы. При этом cypress будет перехватывать запросы и возращать результаты с данными из файлов из папки fixtures. Т.к. иначе мы тестируем не только фронтенд, а и бэкенд. Так же изменения данных на бэке могут сломать тесты (например если изменятся ингредиенты) или мы можем там сломать что нибудь ненужными запросами.

```javascript
     beforeEach(function () {
        cy.intercept("GET", "api/ingredients", { fixture: "ingredients.json" });
      }
```
где ingredients.json - файл в папке fixtures содержащий данные ингредиентов

Подробнее о fixtures можно прочитать в документации https://docs.cypress.io/api/commands/fixture

2023-06-23 05:37 UTC, randomroot commented on cypress/e2e/component.test.cy.ts
> +        cy.visit('http://localhost:3000/')
🟡 **Можно улучшить:**

Открытие страницы вашего сайта можно поместить в блок `beforeEach` (см. https://filiphric.com/cypress-basics-before-beforeeach-after-aftereach)

2023-06-23 05:37 UTC, randomroot commented on src/components/servicies/reducers/constructor-reducer.test.js
> +    "ADD_BUN & ADD_ITEM_TO_CURRENT_LIST & CLEAR_CURRENT_LIST & DECREMENT_CURRENT_CONSTRUCTOR_LIST & DRAG_INSIDE_CONTAINER", ()=>{
🟡 **Можно улучшить:**

Если количество имен вызовов будет увеличиваться, то описание станет слишком громоздким, целесообразно сократить его до минимального варианта, просто описав, что именно тут тестируем, например `Testing constructor reducer`

2023-06-23 05:37 UTC, randomroot commented on cypress/e2e/component.test.cy.ts
> +        cy.get('input[name=password]').type('neznaika')
🟡 **Можно улучшить:**

Постоянные значения в тестах лучше выносить в отдельные константы, чтобы легко их изменять без поиска, где они расположены

2023-06-23 05:37 UTC, randomroot commented on cypress/e2e/component.test.cy.ts
> +        cy.get('body').type('{esc}')
🔴 **Нужно исправить:**

В тесте модального окна следует также проверить: попал ли нужный ингредиент в модальное окно и после нажатия на кнопку ESC исчезло ли оно с экрана

2023-06-25 10:14 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-06-25 10:56 UTC, JavaScriptNoob commented
> 🟢 **Работа принята:**
> 
> Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍
> 
> Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

Спасибо большое !

2023-07-01 18:13 UTC, merged