Sprint2/steg2
JavaScriptNoob/react-burger pull request #6
Opened 2023-03-02 08:44 UTC by JavaScriptNoob

Здравствуйте у меня возникли серьезные проблемы с подсветкой табов, нашел решение на просторах интернета но оно какое то корявое, посоветуйте как исправить.

2023-03-02 09:40 UTC, andryxxa93 requested changes
Здравствуйте! Проделана огромная работа 👍 
- `Dnd` работает отлично - так держать!
- После оформления заказа - очищается конструктор.
- Правильно настроен redux 
- Есть подсвечивание табов при скролле категорий.

Что необходимо исправить:
- У вас экшен на получение ингредиентов называется `GET_INGREDIENTS`. Хотя должен `GET_INGREDIENTS_REQUEST`. Экшен по которому ингредиенты записываются в хранилище называется `REQUEST_CONFIRMED ` хотя по логике должен `GET_INGREDIENTS_SUCCESS`. То же касается и экшенов получения номера заказа.
- Обратите внимание, что при получении ингредиентов они записываются в массив `productData` который так же находится в объекте `productData`. Возможно лучше записывать в `orders` чтобы не дублировать названия и не создавать путаницы. Увидеть это можно если установить расширение для браузера - [redux devtools.](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd) и открыв инструменты разработчика F12 выбрать вкладку `redux` - там вы увидите все экшены и то как они изменяют стейт.
![Снимок экрана 2023-03-02 в 12 08 27](https://user-images.githubusercontent.com/60173362/222383053-306f6606-8c4d-4bf1-8f02-02ecd22545c6.png)
- У всех ингредиентов счетчик показывает - 1, хотя ни одни из них не добавлен в конструктор. Так же при добавлении в конструктор игредиента счетчик не обновляется.
- Если конструктор пуст стоит скрывать или дизейблить кнопку "Оформить заказ".
- Чтобы юзер понимал что делать добавьте для пустого конструктора подсказку - "добавьте булки сюда".
- У вас в хранилище в каждом из модулей находятся поля не относящиеся к этому модулю.
![Снимок экрана 2023-03-02 в 12 23 32](https://user-images.githubusercontent.com/60173362/222386847-4185830d-a75a-40ed-9898-69696c8e22f3.png)
- следует разделить экшены и редьюсеры относящиеся к решению конкретной задачи по файлам
- Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-03-02 09:40 UTC, andryxxa93 commented on src/components/app/App.js
> +    const confirmed = useSelector(state => state.productsData.productsHaveBeenRecieved)
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-03-02 09:40 UTC, andryxxa93 commented on src/components/app/App.js
> +            <div id="portal">
**Можно лучше**
Контейнер для модалки необходимо объявлять в файле `index.html`.

2023-03-02 09:40 UTC, andryxxa93 commented on src/components/modal/modal.js
> +const Modal = (props) => {
**Можно лучше**
props объявлены хотя не используются, их следует удалить, посмотрите во всём проекте

2023-03-02 09:40 UTC, andryxxa93 commented on src/components/servicies/actions/actions.js
> +import {_QUERY} from "../api";
- следует разделить экшены относящиеся к решению конкретной задачи по файлам
    
    ```markdown
    **Надо исправить**
    следует разделить экшены по файлам, на нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктор. Лучше, что бы экшены относящиеся к решению каждой были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавлять новый функционал и плохо, если придется все экшены описывать в одном файле, он будет слишком большой
    
    В текущем приложении можно разделить на следующие файлы:
    - загрузка данных ингредиентов
    - работа конструктора
    - открытие ингредиента в попапе
    - оформление заказа
    ```

2023-03-02 09:40 UTC, andryxxa93 commented on src/components/servicies/reducers/reducers.js
> +import{
**Надо исправить**

со временем приложение будет разрастаться, появится новый функционал, если все будет в одном рельюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например

- загрузка данных ингредиентов
- отправка заказа
- работа конструктора
- открытие модального окна ингредиента

Для объединения редьюсеров используйте combineReducers
https://redux.js.org/api/combinereducers

2023-03-02 09:40 UTC, andryxxa93 commented on src/components/servicies/actions/actions.js
> +    fetch("https://norma.nomoreparties.space/api/orders", {
**Можно лучше**
У вас есть функция `postProductData` которая делает практически то же, что и этот экшен или используйте её или удалить. Так же у вас дублируется код проверки ответа запроса - следует вынести в отдельную функцию.

2023-03-02 09:40 UTC, andryxxa93 commented on src/components/utils/coordAxel.js
> +export const coordAxel = (className) => {
**Можно лучше**
Для подсвечивания таба можно использовать `react-intersection-observer`

```

import { useInView } from "react-intersection-observer";
...

// На каждую категорию с ингредиентами необходимо навесить эти рефы.
const [bunsRef, inViewBuns] = useInView({
    threshold: 0,
  });

  const [mainsRef, inViewFilling] = useInView({
    threshold: 0,
  });
  const [saucesRef, inViewSauces] = useInView({
    threshold: 0,
  });

  React.useEffect(() => {
    if (inViewBuns) {
      setCurrentTab("buns");
    } else if (inViewSauces) {
      setCurrentTab("sauces");
    } else if (inViewFilling) {
      setCurrentTab("mains");
    }
  }, [inViewBuns, inViewFilling, inViewSauces]);

```

2023-03-04 09:47 UTC, andryxxa93 commented
Супер! Вы отлично поработали. Но осталось ещё пару замечаний -

- [ ] Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов. На скриншоте хорошо видно, что несмотря на то, что запрос не прошел, всё равно показывается модальное окно с номером старого заказа. 
<img width="1440" alt="Снимок экрана 2023-03-04 в 12 45 24" src="https://user-images.githubusercontent.com/60173362/222892308-9ff5ec23-57bc-4c3b-9696-bfd34fd4750c.png">
<img width="1440" alt="Снимок экрана 2023-03-04 в 12 45 15" src="https://user-images.githubusercontent.com/60173362/222892310-c44d37f9-bcff-4fbf-a00f-b0a9d8379f6f.png">

- [ ] Обратите внимание, что при получении ингредиентов они записываются в массив productData который так же находится в объекте productData. Возможно лучше записывать в orders чтобы не дублировать названия и не создавать путаницы. Увидеть это можно если установить расширение для браузера - [redux devtools.](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd) и открыв инструменты разработчика F12 выбрать вкладку redux - там вы увидите все экшены и то как они изменяют стейт.

2023-03-04 19:30 UTC, JavaScriptNoob commented
> 
Доброго времени суток и спасибо за комментарии  по поводу очищения содержимого хранилища я слегка не улавливаю сути. Что именно мне надо сделать. Необходимо очищать старые значения по  при закрытии модального окна или мне нужно слушать ошибку при запросе к апи и  в следвствии выводить в модальное окно какую то информацию об ошибке. Не могли бы вы описать алгоритм действий который нужно выполнять.спасибо

2023-03-04 20:19 UTC, JavaScriptNoob commented
> [ ] Обратите внимание, что при получении ингредиентов они записываются в массив productData который так же находится в объекте productData. Возможно лучше записывать в orders чтобы не дублировать названия и не создавать путаницы. Увидеть это можно если установить расширение для браузера - [redux devtools.](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd) и открыв инструменты разработчика F12 выбрать вкладку redux - там вы увидите все экшены и то как они изменяют стейт.
![2023-03-04_21-17-19](https://user-images.githubusercontent.com/26487438/222926923-4a5edb8a-92fd-4949-85cd-70c78199bdab.png)

![2023-03-04_21-16-48](https://user-images.githubusercontent.com/26487438/222926925-126efb8c-f334-46c9-a71f-b82d14e62ec9.png)

Я сделал так что при ошибке и при закрытии модалки у меня очищается номер заказа если я правильно вас понял ваше замечание.

2023-03-05 12:58 UTC, andryxxa93 commented
> > [ ] Обратите внимание, что при получении ингредиентов они записываются в массив productData который так же находится в объекте productData. Возможно лучше записывать в orders чтобы не дублировать названия и не создавать путаницы. Увидеть это можно если установить расширение для браузера - [redux devtools.](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd) и открыв инструменты разработчика F12 выбрать вкладку redux - там вы увидите все экшены и то как они изменяют стейт.
> > ![2023-03-04_21-17-19](https://user-images.githubusercontent.com/26487438/222926923-4a5edb8a-92fd-4949-85cd-70c78199bdab.png)
> 
> ![2023-03-04_21-16-48](https://user-images.githubusercontent.com/26487438/222926925-126efb8c-f334-46c9-a71f-b82d14e62ec9.png)
> 
> Я сделал так что при ошибке и при закрытии модалки у меня очищается номер заказа если я правильно вас понял ваше замечание.

Да, вы всё правильно сделали! Прощу прощения, я не видел вашего вопроса.

2023-03-05 13:00 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-05 22:32 UTC, merged