Sprin 3/steg 1
JavaScriptNoob/react-burger pull request #7
Opened 2023-03-15 21:06 UTC by JavaScriptNoob

Здравствуйте!
Задание довольно объемное я пытался проверить сам вроде все готово. Заранее спасибо за помощь!

2023-03-16 06:22 UTC, andryxxa93 requested changes
Здравствуйте! Проделана огромная работа 👍 

Что понравилось:
- Вы реализовали механизм обновления токена
- Токены записываются согласно тех заданию в куки и localStorage
- Есть защита роутов от неавторизованных пользователей.

- Форма входа, как и форма изменения данных, регистрации и восстановления пароля должна быть отцентрирована посредине страницы. Пожалуйста посмотрите как в фигме.

<img width="954" alt="Снимок экрана 2023-03-16 в 08 51 35" src="https://user-images.githubusercontent.com/60173362/225526970-38d9edbc-d24d-4e53-bcde-2f07448fe5bd.png">

- После успешного прохождения запроса на логин необходимо редиректить на страницу профиля.

<img width="1440" alt="Снимок экрана 2023-03-16 в 08 53 20" src="https://user-images.githubusercontent.com/60173362/225527298-d9ccf5a9-496a-4a08-82e5-8705d61f93a8.png">


- Какой-то лишний текст присутствует на странице профиля и у инпутов не хватает отступов между друг дружкой. В инпутах должны быть данные юзера. 

<img width="878" alt="Снимок экрана 2023-03-16 в 08 55 04" src="https://user-images.githubusercontent.com/60173362/225527675-f7eef711-9710-4dbc-8a7b-6bd4113a37fc.png"> 

- При изменении данных юзера если внесено только имя, то не нужно в тело запроса вставлять другие поля с пустыми строками вместо значений, не то вы получается меняете эти поля на эти значения.  

<img width="742" alt="Снимок экрана 2023-03-16 в 08 58 27" src="https://user-images.githubusercontent.com/60173362/225528063-826e46f3-49bf-4ca1-98fa-143d37ddd7ff.png">

- Авторизация не должно сбрасываться при перезагрузке страницы.

- При запросе на регистрацию вам сервер возвращает токены для нового юзера, так что вы можете его сразу авторизовать. Так же после регистрации необхоидимо делать редирект на главную страницу.

- У вас кнопка "Зарегистрироваться" вместо "Восстановить пароль" на странице логина.

- При вводе каких-то значений в форму изменения данных юзера происходит куча запросов. 

https://user-images.githubusercontent.com/60173362/225529380-d55d42e6-b515-4bb2-9dcd-3b1d24746cf4.mov

- В форме изменения данных дважды встречается инпут  "Имя". Куда вводить пароль непонятно.

- При сохранении новых данных юзера происходит обновление страницы и пользователь попадает на главную страницу.

- Вы реализовали обновление токена - это супер, но после успешного обновления токена необходимо повторять ранее неудавшийся запрос.

- У формы изменения данных не хватает кнопки "Отмена".

- Неавторизованный юзер не должен иметь возможность сделать заказ.

- Роут `reset-password` должен быть доступен только через роут `/forgot-password`.

- На странице профиля отсутствуют ссылки "Профиль" "История заказов" и "Выход".

- При логауте необходимо делать запрос на сервер и передавать токен. Токен при логуате из куков и localStorage необходимо удалять.

- Допишите функцию setCookie - смотрте комментарий к pull-request.

- Чтобы приходящий с сервера токен заносился всегда по пути "/" в куку, нужно в функцию setCookies передавать как значение параметра props аргумент {path="/"}:
setCookie('name', value, { path: '/' }).
Об этом можно прочитать здесь: https://learn.javascript.ru/cookie
Уничтожать токен при логауте пользователя нужно также по пути path: '/'.

Удачных правок!

2023-03-16 06:22 UTC, andryxxa93 commented on src/components/app/App.js
> +                        <Route path="/login" element={<Login/>}/>
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-03-16 06:22 UTC, andryxxa93 commented on src/pages/profile.jsx
> +    });
Из-за того, что не указан список зависимостей - то и происходит куча повторных запросов на получение данных юзера. Так как при внесении данных в форму компонент рендерится  и вместе с ним срабатывает `useEffect`

2023-03-16 06:22 UTC, andryxxa93 commented on src/components/servicies/jwt.js
> +export const storeCookie=(title,payload)=>{
**Необходимо исправить**
Функция setCookie должна быть другой -

```
function setCookie(name, value, options = {}) {

  options = {
    path: '/',
    // при необходимости добавьте другие значения по умолчанию
    ...options
  };

  if (options.expires instanceof Date) {
    options.expires = options.expires.toUTCString();
  }

  let updatedCookie = encodeURIComponent(name) + "=" + encodeURIComponent(value);

  for (let optionKey in options) {
    updatedCookie += "; " + optionKey;
    let optionValue = options[optionKey];
    if (optionValue !== true) {
      updatedCookie += "=" + optionValue;
    }
  }

  document.cookie = updatedCookie;
}
```

https://learn.javascript.ru/cookie

2023-03-18 01:53 UTC, JavaScriptNoob commented
> Здравствуйте! Проделана огромная работа 👍
> 
> Что понравилось:
> 
> * Вы реализовали механизм обновления токена
> * Токены записываются согласно тех заданию в куки и localStorage
> * Есть защита роутов от неавторизованных пользователей.
> 
> Что необходимо исправить:
> 
> * Форма входа, как и форма изменения данных, регистрации и восстановления пароля должна быть отцентрирована посредине страницы. Пожалуйста посмотрите как в фигме.
> 
> <img alt="Снимок экрана 2023-03-16 в 08 51 35" width="954" src="https://user-images.githubusercontent.com/60173362/225526970-38d9edbc-d24d-4e53-bcde-2f07448fe5bd.png">
> 
> * После успешного прохождения запроса на логин необходимо редиректить на страницу профиля.
> 
> <img alt="Снимок экрана 2023-03-16 в 08 53 20" width="1440" src="https://user-images.githubusercontent.com/60173362/225527298-d9ccf5a9-496a-4a08-82e5-8705d61f93a8.png">
> 
> * Какой-то лишний текст присутствует на странице профиля и у инпутов не хватает отступов между друг дружкой. В инпутах должны быть данные юзера.
> 
> <img alt="Снимок экрана 2023-03-16 в 08 55 04" width="878" src="https://user-images.githubusercontent.com/60173362/225527675-f7eef711-9710-4dbc-8a7b-6bd4113a37fc.png">
> 
> * # При изменении данных юзера если внесено только имя, то не нужно в тело запроса вставлять другие поля с пустыми строками вместо значений, не то вы получается меняете эти поля на эти значения.
> 
> <img alt="Снимок экрана 2023-03-16 в 08 58 27" width="742" src="https://user-images.githubusercontent.com/60173362/225528063-826e46f3-49bf-4ca1-98fa-143d37ddd7ff.png">
> 
> * Авторизация не должно сбрасываться при перезагрузке страницы.
> * При запросе на регистрацию вам сервер возвращает токены для нового юзера, так что вы можете его сразу авторизовать. Так же после регистрации необхоидимо делать редирект на главную страницу.
> * У вас кнопка "Зарегистрироваться" вместо "Восстановить пароль" на странице логина.
> * При вводе каких-то значений в форму изменения данных юзера происходит куча запросов.
> 
> * В форме изменения данных дважды встречается инпут  "Имя". Куда вводить пароль непонятно.
> * При сохранении новых данных юзера происходит обновление страницы и пользователь попадает на главную страницу.
> * Вы реализовали обновление токена - это супер, но после успешного обновления токена необходимо повторять ранее неудавшийся запрос.
> * У формы изменения данных не хватает кнопки "Отмена".
> * Неавторизованный юзер не должен иметь возможность сделать заказ.
> * Роут `reset-password` должен быть доступен только через роут `/forgot-password`.
> * На странице профиля отсутствуют ссылки "Профиль" "История заказов" и "Выход".
> * При логауте необходимо делать запрос на сервер и передавать токен. Токен при логуате из куков и localStorage необходимо удалять.
> * Допишите функцию setCookie - смотрте комментарий к pull-request.
> * Чтобы приходящий с сервера токен заносился всегда по пути "/" в куку, нужно в функцию setCookies передавать как значение параметра props аргумент {path="/"}:
>   setCookie('name', value, { path: '/' }).
>   Об этом можно прочитать здесь: https://learn.javascript.ru/cookie
>   Уничтожать токен при логауте пользователя нужно также по пути path: '/'.
> 
> Удачных правок!

Здравствуйте  и большое спасибо за исчерпывающие комментарии ! Я сделал все за исключением оюновления токена при перезагрузке страницы и адаптивных кнопок. Со вторым у меня возникли проблемы в частности как можно передавадь их раздельно если api  нужно передавать все три значения. А в случаи если они передачи одного обновленного жлемента как определить его тип не могли. Заранее благодарю.

2023-03-18 18:27 UTC, JavaScriptNoob commented
@andryxxa93  Здравствуйте вы возможно пропустили мой пул реквест и комментарий

2023-03-18 18:35 UTC, andryxxa93 commented
Супер! Вы отлично потрудились - так держать! Осталось ещё пару замечаний и работа будет принята: 

- Восстановление пароля не работает, на странице `reset-password` после ввода пароля сразу идёт перенаправление на главную страницу.
- В шапке панели навигации должны быть активна та ссылка на маршрут, где сейчас находится пользователь. Ссылка должна оставаться активной, если пользователь попадает на вложенные динамические маршруты. Например на "Историю заказов". Сейчас у вас активные все ссылки сразу судя по стилю.
- После изменения данных идёт перенаправление на главную страницу. Это не нужно делать.
- Кнопки "Очистить" нет на странице профиля, там должна быть кнопка "Отмена". И она должна отменять изменения, т.е приводить к изначальному состоянию, а не очищать форму.
- У вас в компоненте Profile идёт сразу два запроса в `useEffect`- один на получение данных юзера, а второй называется `refetchUser`, который по сути делает то же самое.  
- У вас обновляется токен - это отлично, но после обновления токена необходимо повторять ранее неудавшийся запрос - будь то изменение данных или просто получение данных.

<img width="1440" alt="Снимок экрана 2023-03-18 в 21 33 06" src="https://user-images.githubusercontent.com/60173362/226129204-a48e0726-21cd-4636-9e92-35a64b816f76.png">


**Можно лучше**
- Юзер должен иметь возможность изменить данные без заполнения всех полей формы. 
- После регистрации необходимо перенаправлять юзера на главную страницу в уже авторизованном статусе.

P.S. вам не нужно передавать всегда все три поля для изменения данных, можно и одно и два - api примет такой запрос и обработает.

2023-03-18 18:37 UTC, JavaScriptNoob commented
@andryxxa93  P.S. вам не нужно передавать всегда все три поля для изменения данных, можно и одно и два - api примет такой запрос и обработает.
А как такое реализовать учитывая что я определяю количество аргументов и тому подобное в экшене

2023-03-19 16:25 UTC, JavaScriptNoob commented
@andryxxa93  Вроде все сделал но  я честно не понимаю как протестировать  обновление токена после истечения срока действия токена

2023-03-19 16:31 UTC, JavaScriptNoob commented on src/pages/profile.jsx
>                                  <Button
Восстановление текста по кнопке   отмена

2023-03-19 16:31 UTC, JavaScriptNoob commented on src/components/servicies/actions/update-user-details-action.js
>                          user: res.user,
Обновление данных после смены значений и позитивного ответа запроса

2023-03-19 16:31 UTC, JavaScriptNoob commented on src/pages/reset-password.jsx
> -    if (resetStatus) {
Проверка на успешность обновления пароля и переход

2023-03-19 16:31 UTC, JavaScriptNoob commented on src/components/app-header/app-header.js
> -                <NavLink exact to="/profile" className={({ isActive, isPending }) =>
Подсветка навигации в зависимости от активного пути

2023-03-19 16:31 UTC, JavaScriptNoob commented on src/components/servicies/reducers/user-reducer.js
Перенос ForgotUser в CurrentUser  суля по логике они взаимосвязаны но редьюсер стал огромен

2023-03-19 16:31 UTC, JavaScriptNoob commented on src/pages/forgot-password.jsx
> +    const success = useSelector( selectorUser ).forgotPasswordSuccess
Немножко другие условия для роутинга

2023-03-19 16:31 UTC, JavaScriptNoob commented on src/pages/forgot-password.jsx
> +    const success = useSelector( selectorUser ).forgotPasswordSuccess
Немножко другие условия для роутинга

2023-03-19 16:31 UTC, JavaScriptNoob commented on src/components/servicies/actions/update-user-details-action.js
>                  if (res.message === 'jwt expired') {
Попробовал делать запрос после обновления токена

2023-03-20 07:13 UTC, andryxxa93 commented
Чтобы неудавшийся запрос повторялся после обновления токена вы можете сделать такую универсальную функцию -
Которая будет принимать `url` и опции запроса. В случае ошибки с токеном она повторит неудавшийся запрос. Вам нужно её использовать везде где используется accessToken.

```
export const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options);
    return await checkReponse(res);
  } catch (err) {
    if (err.message === "jwt expired") {
      const refreshData = await refreshToken();
      if (!refreshData.success) {
        Promise.reject(refreshData);
      }
      localStorage.setItem("refreshToken", refreshData.refreshToken);
      setCookie("accessToken", refreshData.accessToken);
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options);
      return await checkReponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};

```

Если у вас что-то не получается вы всегда можете обратиться к своему наставнику.

Удачных правок!

2023-03-20 07:14 UTC, andryxxa93 commented
Воспроизвести проблему с токеном можно авторизовавшись и перейдя в личный кабинет подождать 20 минут и попробовать изменить данные пользователя.

2023-03-22 06:57 UTC, JavaScriptNoob commented
![image](https://user-images.githubusercontent.com/26487438/226825466-5a4789bb-e29a-4d86-abe8-a8f87fc9d050.png)
Вроде бы заработало, спасибо за подсказку!

2023-03-22 19:56 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

**Можно лучше**
В проекте осталось много console.log - считается хорошим тоном удалять их перед отправкой на github

2023-03-30 14:09 UTC, closed without merging